apiVersion: apps/v1
kind: Deployment

metadata:
  name: axion-ingestion-pod

spec:
  replicas: 1

  selector:
    matchLabels:
      app: axion-ingestion-pod

  template:
    metadata:
      labels:
        app: axion-ingestion-pod
        azure.workload.identity/use: "true"

    spec:
      serviceAccountName: axion-keyvault-sa

      containers:
        - name: axion-ingestion-pod

          image: sammyacr.azurecr.io/ingestion:v1

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            # PostgreSQL username from Key Vault → Kubernetes Secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: axion-postgres-secret
                  key: POSTGRES_USER

            # PostgreSQL password from Key Vault → Kubernetes Secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: axion-postgres-secret
                  key: POSTGRES_PASSWORD

            # PostgreSQL Kubernetes Service
            - name: POSTGRES_HOST
              value: "postgresql-service"

            - name: POSTGRES_PORT
              value: "5432"

            - name: POSTGRES_DB
              value: "postgresdb"

          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: axion-keyvault-secrets