apiVersion: apps/v1
kind: Deployment

metadata:
  name: axion-data-simulator

spec:
  replicas: 1

  selector:
    matchLabels:
      app: axion-data-simulator

  template:
    metadata:
      labels:
        app: axion-data-simulator

    spec:
      containers:
        - name: axion-data-simulator
          image: sammyacr.azurecr.io/simulator:v1
          imagePullPolicy: Always