apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: axion-keyvault-secrets
  namespace: default

spec:
  provider: azure

  parameters:
    clientID: "57adaacc-2aaa-44ea-85ad-7121cff8beb2"
    keyvaultName: "axion-kv-dev"
    tenantId: "00a6a2f2-9cac-40b2-92fe-12183743f0d2"

    objects: |
      array:
        - |
          objectName: postgres-username
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: pgadmin-username
          objectType: secret
        - |
          objectName: pgadmin-password
          objectType: secret

  secretObjects:
    - secretName: axion-postgres-secret
      type: Opaque
      data:
        - objectName: postgres-username
          key: POSTGRES_USER
        - objectName: postgres-password
          key: POSTGRES_PASSWORD

    - secretName: axion-pgadmin-secret
      type: Opaque
      data:
        - objectName: pgadmin-username
          key: PGADMIN_DEFAULT_EMAIL
        - objectName: pgadmin-password
          key: PGADMIN_DEFAULT_PASSWORD