apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-server

  template:
    metadata:
      labels:
        app: postgresql-server
    spec:    
      containers:
      - name: postgresql-server
        image: postgres:17.10
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_PASSWORD
            value: "admin"
          - name: POSTGRES_DB
            value: "mydatabase"